# -*- coding: utf-8 -*-
"""อัปเกรดโปรเจกต์ QA คำแปล

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BnhmLN2wqH34p6Eqs98v6g6swNfR8ank
"""

import streamlit as st
import pandas as pd
import json
import io
from pathlib import Path

# Import readers & rules (ตรวจสอบให้แน่ใจว่า path ไฟล์เหล่านี้ถูกต้องใน GitHub)
from readers.excel_reader import read_excel
from readers.xliff_reader import read_xliff
from readers.tmx_reader import read_tmx
from rules.placeholder import check_placeholders
from rules.glossary import check_glossary
from rules.missing import check_missing
from rules.numbers import check_numbers
from rules.spelling import check_spelling
from rules.encoding import check_encoding
from rules.style_guide import check_style_guide
from rules.length import check_length
from exporters.export import export_excel, export_csv

st.set_page_config(
    page_title="Translation QA Tool",
    page_icon="🔍",
    layout="wide",
)

# --- ส่วนของการประมวลผล QA ---
def run_qa_process(df, glossary, style_guide):
    results = []
    results += check_missing(df)
    results += check_placeholders(df)
    results += check_numbers(df)
    results += check_glossary(df, glossary)
    results += check_spelling(df)
    results += check_encoding(df, style_guide)
    results += check_style_guide(df, style_guide)
    results += check_length(df, style_guide)
    return results

# --- UI Layout ---
st.title("🔍 Translation Quality Assurance Tool")

if "results" not in st.session_state:
    st.session_state.results = []
if "glossary" not in st.session_state:
    st.session_state.glossary = []
if "style_guide" not in st.session_state:
    st.session_state.style_guide = {
        "encoding": "UTF-8",
        "max_length_ratio": 3.0,
        "tone": "ทางการ"
    }

tab_run, tab_glossary, tab_config = st.tabs(["🚀 Run QA", "📕 Glossary", "⚙️ Settings"])

with tab_run:
    uploaded_file = st.file_uploader("อัปโหลดไฟล์ (Excel, XLIFF, TMX)", type=["xlsx", "xliff", "tmx"])

    if uploaded_file:
        # เลือก Reader ตามนามสกุลไฟล์
        ext = Path(uploaded_file.name).suffix.lower()
        if ext == ".xlsx": df = read_excel(uploaded_file)
        elif ext == ".xliff": df = read_xliff(uploaded_file)
        elif ext == ".tmx": df = read_tmx(uploaded_file)

        if df is not None:
            st.success(f"โหลดข้อมูลสำเร็จ: {len(df)} segments")

            if st.button("เริ่มการตรวจสอบ (Run QA)", type="primary"):
                with st.spinner("กำลังตรวจสอบ..."):
                    res = run_qa_process(df, st.session_state.glossary, st.session_state.style_guide)
                    st.session_state.results = res

                if not res:
                    st.balloons()
                    st.success("ไม่พบข้อผิดพลาด!")
                else:
                    # --- ส่วนที่แก้ไข: ใช้ Native Streamlit Chart แทน Plotly ---
                    st.markdown("### 📊 สรุปผลการตรวจสอบ")
                    df_res = pd.DataFrame(res)

                    col_m1, col_m2 = st.columns(2)
                    with col_m1:
                        st.metric("จำนวนปัญหาที่พบ", len(df_res))
                    with col_m2:
                        # แสดงกราฟแท่งสรุป Severity
                        severity_counts = df_res['severity'].value_counts()
                        st.bar_chart(severity_counts)

                    st.divider()

                    # แสดงรายละเอียดปัญหา
                    for item in res:
                        with st.expander(f"[{item['severity']}] แถวที่ {item['row']+1}: {item['rule']}"):
                            st.write(f"**Source:** {item['source']}")
                            st.write(f"**Target:** {item['target']}")
                            st.warning(f"💡 {item['message']}")

# --- Tab อื่นๆ คงไว้ตามเดิม ---
with tab_glossary:
    st.subheader("จัดการคำศัพท์ (Glossary)")
    edited_g = st.data_editor(st.session_state.glossary, num_rows="dynamic", use_container_width=True)
    if st.button("บันทึก Glossary"):
        st.session_state.glossary = edited_g
        st.toast("บันทึกแล้ว!")

with tab_config:
    st.subheader("ตั้งค่า Style Guide")
    # (เพิ่มโค้ดตั้งค่าตามที่คุณมีเดิม...)