# -*- coding: utf-8 -*-
"""อัปเกรดโปรเจกต์ QA คำแปล

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BnhmLN2wqH34p6Eqs98v6g6swNfR8ank
"""

import streamlit as st
import pandas as pd
import json
import io
import re
import plotly.express as px  # เพิ่มเพื่อทำกราฟสรุปผล
from pathlib import Path
from lxml import etree
from openpyxl.styles import PatternFill, Font

# ==========================================
# CONSTANTS & CONFIGURATIONS
# ==========================================

THAI_MISSPELLINGS = {
    "คลิ๊ก": "คลิก", "โปรแกรมม์": "โปรแกรม", "อีเมล์": "อีเมล",
    "อินเตอร์เน็ต": "อินเทอร์เน็ต", "เว็บไซท์": "เว็บไซต์",
    "แอพพลิเคชั่น": "แอปพลิเคชัน", "อัพโหลด": "อัปโหลด",
    "พาสเวิร์ด": "รหัสผ่าน", "ล็อคอิน": "เข้าสู่ระบบ", "บัค": "บัก",
}

PLACEHOLDER_PATTERNS = [
    r"\{[\w\d_]+\}", r"%[sd\d]", r"<[^>]+>", r"\[\[[\w\d_]+\]\]", r"%%[\w\d_]+%%",
]

ALL_PATTERNS = [
    ("ตัวเลข", re.compile(r"\b\d[\d,\.]*\b"), "Critical"),
    ("วันที่", re.compile(r"\b\d{1,2}[\/\-\.]\d{1,2}[\/\-\.]\d{2,4}\b"), "Critical"),
    ("สกุลเงิน", re.compile(r"[\$\€\£\฿]\s?\d[\d,\.]*|\d[\d,\.]*\s?(?:USD|EUR|THB|GBP)"), "Critical"),
    ("Version", re.compile(r"\bv?\d+\.\d+(?:\.\d+)?\b"), "Major"),
    ("Email", re.compile(r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+\b"), "Major"),
    ("URL", re.compile(r"https?://\S+"), "Major"),
]

# ==========================================
# CORE QA FUNCTIONS (รวมจากไฟล์ย่อย)
# ==========================================

def get_qa_issues(df, glossary, style_guide, active_rules):
    issues = []

    for idx, row in df.iterrows():
        src = str(row.get("source", "")).strip()
        tgt = str(row.get("target", "")).strip()

        # 1. Missing Translation
        if active_rules['missing'] and src and not tgt:
            issues.append({"row": idx, "source": src, "target": tgt, "rule": "Missing", "severity": "Major", "message": "ยังไม่ได้แปล"})

        if not tgt: continue

        # 2. Placeholders
        if active_rules['placeholder']:
            src_ph = []
            for pat in PLACEHOLDER_PATTERNS: src_ph += re.findall(pat, src)
            tgt_ph = []
            for pat in PLACEHOLDER_PATTERNS: tgt_ph += re.findall(pat, tgt)

            missing = [p for p in src_ph if p not in tgt_ph]
            if missing:
                issues.append({"row": idx, "source": src, "target": tgt, "rule": "Placeholder", "severity": "Critical", "message": f"Placeholder หาย: {', '.join(set(missing))}"})

        # 3. Numbers & Data
        if active_rules['numbers']:
            for label, pat, sev in ALL_PATTERNS:
                s_vals = set(pat.findall(src))
                t_vals = set(pat.findall(tgt))
                diff = s_vals - t_vals
                if diff:
                    issues.append({"row": idx, "source": src, "target": tgt, "rule": label, "severity": sev, "message": f"{label} ไม่ตรง: {', '.join(diff)}"})

        # 4. Glossary
        if active_rules['glossary']:
            for entry in glossary:
                if str(entry['source']).lower() in src.lower() and str(entry['target']) not in tgt:
                    issues.append({"row": idx, "source": src, "target": tgt, "rule": "Glossary", "severity": entry['severity'], "message": f"ควรใช้ '{entry['target']}' สำหรับ '{entry['source']}'"})

        # 5. Spelling
        if active_rules['spelling']:
            for wrong, right in THAI_MISSPELLINGS.items():
                if wrong in tgt:
                    issues.append({"row": idx, "source": src, "target": tgt, "rule": "Spelling", "severity": "Minor", "message": f"สะกดผิด: '{wrong}' -> '{right}'"})

    return issues

# ==========================================
# READERS & EXPORTERS
# ==========================================

def load_data(file):
    ext = Path(file.name).suffix.lower()
    try:
        if ext == ".xlsx": return pd.read_excel(file).fillna("")
        elif ext in [".xliff", ".tmx"]:
            tree = etree.parse(file)
            # Logic การดึงข้อมูลแบบ Simple สำหรับตัวอย่าง
            rows = [{"source": el.findtext(".//source") or "", "target": el.findtext(".//target") or ""}
                    for el in tree.xpath("//*[local-name()='trans-unit' or local-name()='tu']")]
            return pd.DataFrame(rows)
    except Exception as e:
        st.error(f"Error loading file: {e}")
    return None

# ==========================================
# MAIN APP INTERFACE
# ==========================================

st.set_page_config(page_title="LQA Pro | Translation Quality Assurance", layout="wide")

# Sidebar: Settings
with st.sidebar:
    st.title("🛠 QA Settings")
    st.subheader("Rules Selection")
    active_rules = {
        'placeholder': st.checkbox("Placeholders", value=True),
        'glossary': st.checkbox("Glossary Consistency", value=True),
        'missing': st.checkbox("Missing Translation", value=True),
        'numbers': st.checkbox("Numbers & Entities", value=True),
        'spelling': st.checkbox("Thai Spelling", value=True),
    }

    st.divider()
    if st.button("Clear Cache & Session"):
        st.session_state.clear()
        st.rerun()

# Tabs
t_run, t_glossary, t_guide = st.tabs(["🚀 Run QA", "📕 Glossary Manager", "📜 Style Guide"])

with t_run:
    col1, col2 = st.columns([1, 2])

    with col1:
        uploaded_file = st.file_uploader("Upload translation file", type=["xlsx", "xliff", "tmx"])
        if uploaded_file:
            df = load_data(uploaded_file)
            if df is not None:
                st.success(f"Loaded {len(df)} segments")
                if st.button("▶ Start QA Process", type="primary", use_container_width=True):
                    results = get_qa_issues(df, st.session_state.get('glossary', []), {}, active_rules)
                    st.session_state.qa_results = results

    with col2:
        if "qa_results" in st.session_state:
            res = st.session_state.qa_results
            if not res:
                st.balloons()
                st.success("No issues found! Perfect translation.")
            else:
                # Dashboard
                df_res = pd.DataFrame(res)

                c1, c2 = st.columns([1, 1])
                with c1:
                    st.metric("Total Issues", len(df_res))
                    st.metric("Critical", len(df_res[df_res.severity == "Critical"]))
                with c2:
                    fig = px.pie(df_res, names='severity', color='severity',
                                 color_discrete_map={'Critical':'#e74c3c', 'Major':'#f39c12', 'Minor':'#f1c40f'})
                    fig.update_layout(margin=dict(t=0, b=0, l=0, r=0), height=150, showlegend=False)
                    st.plotly_chart(fig, use_container_width=True)

                st.divider()

                # Filters
                f_sev = st.multiselect("Filter Severity", ["Critical", "Major", "Minor"], default=["Critical", "Major"])

                # Result Display
                for _, row in df_res[df_res.severity.isin(f_sev)].iterrows():
                    with st.expander(f"[{row.severity}] Row {row.row + 1}: {row.rule}"):
                        st.markdown(f"**Source:** `{row.source}`")
                        st.markdown(f"**Target:** `{row.target}`")
                        st.info(f"💡 {row.message}")

with t_glossary:
    st.subheader("Current Glossary")
    if 'glossary' not in st.session_state:
        st.session_state.glossary = [
            {"source": "Cancel", "target": "ยกเลิก", "severity": "Major"},
            {"source": "Settings", "target": "การตั้งค่า", "severity": "Minor"}
        ]

    edited_g = st.data_editor(st.session_state.glossary, num_rows="dynamic", use_container_width=True)
    if st.button("Update Glossary"):
        st.session_state.glossary = edited_g
        st.toast("Glossary Updated!")

# Footer
st.markdown("---")
st.caption("LQA Pro v1.2 | Built for Professional Translators & Reviewers")